spring:
    config:
        import:
            - optional:file:.env[.properties]
    application:
        name: X3_Post_MS
    data:
        mongodb:
            host: ${MONGO_HOST}
            port: ${MONGO_PORT}
            username: ${MONGO_USERNAME}
            password: ${MONGO_PASSWORD}
            database: ${MONGO_BASENAME}
            authentication-database: admin
mongock:
    migration-scan-package: com.unknown.post.changelogs

server:
    port: ${PORT}
    gateway: ${GATEWAY}

logging:
    level:
        org.springframework: INFO
        com.unknown.post: DEBUG
    file:
        name: src/main/resources/logging/user-ms.log
    logback:
        rollingpolicy:
            max-file-size: 10MB
            max-history: 10

springdoc:
    swagger-ui:
        enabled: true
        path: /post/swagger.html
    api-docs:
        path: /post/v3/api-docs/swagger-config