spring:
    config:
        import:
            - optional:file:.env[.properties]
    application:
        name: X3_Post_MS
    data:
        mongodb:
            host: ${PSQL_HOST}
            port: ${PSQL_PORT}
            username: ${PSQL_USERNAME}
            password: ${PSQL_PASSWORD}
            database: ${PSQL_BASENAME}
    liquibase:
        change-log: db/changelog/db.changelog-master.yml
        enabled: true

server:
    port: ${PORT}

logging:
    level:
        org.springframework: INFO
        com.unknown.post: DEBUG
    file:
        name: src/main/resources/logging/user-ms.log
    logback:
        rollingpolicy:
            max-file-size: 10MB
            max-history: 10

springdoc:
    swagger-ui:
        enabled: true
        path: /swagger.html
